#!/bin/bash
set -e
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

mkdir -p "$DIR/bin"

# Build and run evaluator tests
gcc \
    "$DIR/../my-project/tokens.c" \
    "$DIR/../my-project/evaluator.c" \
    "$DIR/../my-project/assets/graphics.c" \
    "$DIR/evaluator.c" \
    -I"$DIR/../my-project" \
    -o"$DIR/bin/evaluator"

$DIR/bin/evaluator